#!/usr/bin/env bash
# TODO: All the paths need to change on final
## TO USE THIS SCRIPT PASTE THE FOLLOWING INTO THE TERMINAL:

# bash -c "$(curl -s https://raw.githubusercontent.com/Modular-Dev/starphleet/master/webinstall)"

##############################################################################
## Author:          Benjamin Hudgens
## Date:            March 18, 2015
##
## Description:     Fully Deploy starphleet from the command line
##
##############################################################################
## Locations to this repo
STARPHLEET_REPO=${STARPHLEET_REPO:-"https://github.com/Modular-Dev/starphleet.git"}
STARPHLEET_BRANCH=${STARPHLEET_BRANCH:-master}

##############################################################################
## Main Foo
##############################################################################

[ -n "${HEADQUARTERS_URL}" ] || read -p "Please paste the SSH git URL to your headquarters:  " HEADQUARTERS_URL

# Run Upgrade before before installing packages - which fixes this error
# https://github.com/lxc/lxc/issues/247
sudo add-apt-repository ppa:ubuntu-lxc/lxc-lts -y
sudo sed -i -e 's/us-east-1.ec2.archive.ubuntu.com\|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
apt-get update --fix-missing -y && apt-get install -y git
# Now grab this repo
git clone -b "${STARPHLEET_BRANCH}" "${STARPHLEET_REPO}"
# Head into scripts
cd starphleet/scripts
# Move launcher into place
cp ./starphleet-launcher /usr/bin
# Let the magic begin
./starphleet-install
# Set the headquarters
starphleet-headquarters "${HEADQUARTERS_URL}"

source `which tools`

cat << EOF

NOTICE:

Installation is not finished.

You need to copy your GitHub ssh private key to:

   ${PRIVATE_KEYS}

EOF
